/** Insurance verification call worksheet (paper form layout). */

export function createEmptyCallScriptForm() {
  return {
    csDate: '',
    csInitials: '',
    patientName: '',
    patientDob: '',
    insured: '',
    insuranceLevel: '',
    insuranceName: '',
    insurancePhone: '',
    insuranceId: '',
    spokeWith: '',
    groupNumber: '',
    callRefNumber: '',
    coeFacilityRequired: '',
    facilityLhhNetwork: '',
    facilityPrmcNetwork: '',
    facilityNote: '',
    effectiveDate: '',
    planType: '',
    definiteExclusion: '',
    pcpReferralRequired: '',
    pcpName: '',
    referralRequested: '',
    referralFrom: '',
    referralReceived: '',
    egdAuthRequired: '',
    echoAuthRequired: '',
    dopplerAuthRequired: '',
    fibroscanAuthRequired: '',
    thirdPartyAuthPortal: '',
    bariatricsInPtAuthReq: '',
    plasticsAuthReq: '',
    inNetOvCopay: '',
    inNetDeductible: '',
    inNetDeductibleRem: '',
    inNetCoins: '',
    inNetOop: '',
    inNetOopRem: '',
    outNetOvCopay: '',
    outNetDeductible: '',
    outNetDeductibleRem: '',
    outNetCoins: '',
    outNetOop: '',
    outNetOopRem: '',
    reqsBariatricWeightBmi: '',
    generalNotes: '',
    comorbiditiesNotes: '',
    dietVisitsReq: '',
    preDrcrReq: '',
    benefitsPrinted: '',
    cardPrinted: '',
    finalNote: '',
  }
}
