/**
 * Field groups matching clinicausuarios/index.html extracted section order and labels.
 * `key` maps to React state (camelCase in medauthForm).
 */

export const CLINICA_FORM_SECTIONS = [
  {
    id: 'id',
    label: 'Insurance Identification',
    icon: 'badge',
    color: 'var(--primary-light)',
    fields: [
      { key: 'insuranceCompany', label: 'Insurance Company Name', span: 2, placeholder: 'Ambetter · Blue Cross BlueShield · Amerigroup · Molina · Christus...' },
      { key: 'subscriberName', label: 'Subscriber Name (policyholder)', placeholder: 'Subscriber full name' },
      { key: 'memberName', label: 'Member Name', placeholder: 'Patient name on card' },
      { key: 'memberId', label: 'Member ID / ID # ★', placeholder: 'Member number (most important)' },
      { key: 'subscriberId', label: 'Subscriber ID / Subscriber #', placeholder: 'Subscriber number' },
      { key: 'groupNumber', label: 'Group Number / Group No. ★', placeholder: 'Group number' },
      { key: 'planName', label: 'Plan Name — full plan name', span: 2, placeholder: 'E.g. Ambetter Balanced Care 1 + Vision + Adult Dental' },
      { key: 'planType', label: 'Plan Type', placeholder: 'PPO / HMO / CHIP / EPO / HDHP...' },
      { key: 'benefitPlan', label: 'Benefit Plan Code', placeholder: 'E.g. HIOPT' },
      { key: 'effectiveDate', label: 'Effective Date', placeholder: 'MM/DD/YYYY' },
      { key: 'dob', label: 'Date of Birth / DOB', placeholder: 'Policyholder date of birth' },
      { key: 'network', label: 'Network', placeholder: 'In Network Only / Out of Network...' },
      { key: 'coverage', label: 'Type of Coverage', placeholder: 'CHIP / Individual / Family / TX-EX...' },
      { key: 'dependents', label: 'Dependents (additional members on the policy)', span: 2, placeholder: 'E.g. Dependent One · Dependent Two · Member 1, Member 2...' },
    ],
  },
  {
    id: 'copay',
    label: 'Medical plan copays',
    icon: 'medication',
    color: 'var(--accent)',
    fields: [
      { key: 'copayPCP', label: 'PCP / Primary Care Office Visit', placeholder: 'E.g. $20' },
      { key: 'copaySpecialist', label: 'Specialist / Specialist Office Visit', placeholder: 'E.g. $40' },
      { key: 'copayEr', label: 'Emergency Room (ER)', placeholder: 'E.g. $150' },
      { key: 'copayUrgent', label: 'Urgent Care', placeholder: 'E.g. $50' },
      { key: 'deductible', label: 'Deductible (Med/Rx)', placeholder: 'E.g. $2,000' },
      { key: 'coinsurance', label: 'Coinsurance (Med/Rx)', placeholder: 'E.g. 20%' },
    ],
  },
  {
    id: 'rx',
    label: 'Pharmacy Plan / Prescription Drugs',
    icon: 'medication',
    color: 'var(--secondary)',
    fields: [
      { key: 'rxBin', label: 'RxBIN / Rx BIN#', placeholder: 'E.g. 610097 / 008019' },
      { key: 'rxPcn', label: 'RxPCN / Rx PCN', placeholder: 'E.g. MEDDADV' },
      { key: 'rxGroup', label: 'RxGRP / Rx Group', placeholder: 'E.g. RX1234' },
      { key: 'rxAdmin', label: 'Pharmacy Administrator', placeholder: 'E.g. Express Scripts' },
      { key: 'rxGeneric', label: 'Generic Drugs copay', placeholder: 'E.g. $5' },
      { key: 'rxBrand', label: 'Preferred Brand Drugs copay', placeholder: 'E.g. $40' },
      { key: 'rxNonPref', label: 'Non-Preferred Brand Drugs copay', placeholder: 'E.g. $75' },
      { key: 'rxSpecialty', label: 'Specialty Drugs copay', placeholder: 'Specialty Drugs' },
    ],
  },
  {
    id: 'pcp',
    label: 'PCP & Provider',
    icon: 'stethoscope',
    color: 'var(--text-secondary)',
    fields: [
      { key: 'pcpName', label: 'PCP Name', placeholder: 'Primary care physician name' },
      { key: 'pcpPhone', label: 'PCP Phone', placeholder: 'PCP phone number' },
      { key: 'pcpEffDate', label: 'PCP Effective Date', placeholder: 'Start date with PCP' },
      { key: 'providerGroup', label: 'Provider Group', placeholder: 'Physician provider group' },
      { key: 'providerPhone', label: 'Provider Phone', placeholder: 'Provider phone number' },
      { key: 'chipNum', label: 'CHIP Perinate Number', placeholder: 'Amerigroup/CHIP cards only' },
    ],
  },
  {
    id: 'phones',
    label: 'Back of Card Phone Numbers',
    icon: 'call',
    color: 'var(--accent)',
    fields: [
      {
        key: 'phoneCustomerService',
        label: 'Member Services ★ — main number to call',
        span: 2,
        type: 'tel',
        placeholder: 'Member Services number from card back',
        highlight: true,
        hint: 'This number will appear in the Call Script on Step 2',
      },
      { key: 'phonePreauth', label: 'Prior Authorization / Pre-Auth Phone', placeholder: 'Prior authorization phone number' },
      { key: 'phonePharmacy', label: 'Pharmacy Phone', placeholder: 'Pharmacy phone number' },
      { key: 'phoneNurse', label: '24-Hour Nurse HelpLine', placeholder: '24h nurse line' },
      { key: 'phoneBehavioral', label: 'Behavioral Health Phone', placeholder: 'Mental health / behavioral health' },
      { key: 'website', label: 'Insurance Website', span: 2, placeholder: 'www.insurancecompany.com' },
    ],
  },
]

export const FRONT_OCR_CLEAR_KEYS = [
  'insuranceCompany',
  'subscriberName',
  'memberName',
  'memberId',
  'subscriberId',
  'groupNumber',
  'planName',
  'planType',
  'benefitPlan',
  'effectiveDate',
  'dob',
  'network',
  'coverage',
  'dependents',
  'copayPCP',
  'copaySpecialist',
  'copayEr',
  'copayUrgent',
  'deductible',
  'coinsurance',
  'rxBin',
  'rxPcn',
  'rxGroup',
  'rxAdmin',
  'rxGeneric',
  'rxBrand',
  'rxNonPref',
  'rxSpecialty',
  'pcpName',
  'pcpPhone',
  'pcpEffDate',
  'providerGroup',
  'providerPhone',
  'chipNum',
]

export const BACK_OCR_CLEAR_KEYS = [
  'phoneCustomerService',
  'phonePreauth',
  'phonePharmacy',
  'phoneNurse',
  'phoneBehavioral',
  'website',
]
