/** Patient intake form (paper INTAKE) — serializable for Firestore / reports. */

export function createEmptyIntakeForm() {
  return {
    patientName: '',
    addressLine1: '',
    addressLine2: '',
    patientPhone: '',
    email: '',
    gender: '',
    patientDob: '',
    patientSs: '',
    intakeDate: '',
    referredBy: '',
    staffName: '',
    height: '',
    weight: '',
    bmi: '',
    primaryCareProvider: '',
    primaryInsurance: '',
    primaryInsurancePhone: '',
    primaryInsuredName: '',
    primaryInsuredSs: '',
    primaryInsuredDob: '',
    primaryId: '',
    primaryGroup: '',
    secondaryInsurance: '',
    secondaryInsurancePhone: '',
    secondaryInsuredName: '',
    secondaryInsuredSs: '',
    secondaryInsuredDob: '',
    secondaryId: '',
    secondaryGroup: '',
    selfPay: '',
    comorbidDiabetic: false,
    comorbidHbp: false,
    comorbidChol: false,
    comorbidThyroid: false,
    comorbidSleepApnea: false,
    healthIssuesWeight: '',
    prevSurgery: '',
    interestedRevision: '',
    interestedSkinRemoval: '',
    needHerniaRepair: '',
    surgerySurgeonName: '',
    surgeryDateYear: '',
    surgeryStartWt: '',
    surgeryEndWt: '',
    surgeryComments: '',
  }
}
